
# temporary variable to understand what is happening
def PrintVariables(l):
    print(f'Principal {l.principal}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Duration {l.duration}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Interest {l.interest}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Inflation {l.inflation}')
    print('============================')
    print('============================')
    print('============================')
    print(f'CPI {l.CPI}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Cost {l.cost}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Inflation index list {l.inflation_index_list}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Annuity factor list {l.annuity_factor_list}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Principal list {l.principal_list}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Payment list {l.payment_list}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Interest list {l.interest_list}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Payment of capital {l.payment_of_capital_list}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Step {l.step}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Total payment list {l.total_payment_list}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Monthly interest {l.monthly_interest}')
    print('============================')
    print('============================')
    print('============================')
    print(f'Monthly inflation {l.monthly_inflation}')
